// gsgen scans a package directory for structs that opt into reflection,
// either by carrying a `gs:"..."` field tag or a "gs:register" doc comment,
// and generates the gs.Register calls for them.
//
// It also weaves: an unexported method named xxxImpl on an opted-in struct
// gets a generated exported Xxx trampoline that consults the gs patch table
// before calling the impl, so even compiled call sites become patchable at
// runtime.
//
// Usage, from the target package:
//
//	//go:generate go run github.com/dappermint/glass/cmd/gsgen
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"go/types"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"
)

type paramGroup struct {
	names []string
	typ   string
}

type weaveFn struct {
	recvName  string
	recvType  string
	implName  string
	wovenName string
	params    []paramGroup
	results   []string
	variadic  bool // last param is ...T
}

func main() {
	log.SetFlags(0)
	log.SetPrefix("gsgen: ")
	dir := flag.String("dir", ".", "package directory to scan")
	out := flag.String("out", "gs_gen.go", "output file name")
	gspkg := flag.String("gspkg", "github.com/dappermint/glass/gs", "import path of the gs package")
	flag.Parse()

	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, *dir, func(fi fs.FileInfo) bool {
		name := fi.Name()
		return !strings.HasSuffix(name, "_test.go") && name != *out
	}, parser.ParseComments)
	if err != nil {
		log.Fatal(err)
	}

	var pkgName string
	var names []string
	var files []*ast.File
	for name, pkg := range pkgs {
		if strings.HasSuffix(name, "_test") {
			continue
		}
		pkgName = name
		for _, file := range pkg.Files {
			files = append(files, file)
			names = append(names, scanFile(file)...)
		}
	}
	if pkgName == "" {
		log.Fatalf("no Go package found in %s", *dir)
	}
	sort.Strings(names)

	eligible := map[string]bool{}
	for _, n := range names {
		eligible[n] = true
	}
	var weaves []weaveFn
	for _, file := range files {
		weaves = append(weaves, scanImpls(file, eligible)...)
	}
	sort.Slice(weaves, func(i, j int) bool {
		if weaves[i].recvType != weaves[j].recvType {
			return weaves[i].recvType < weaves[j].recvType
		}
		return weaves[i].wovenName < weaves[j].wovenName
	})

	if len(names) == 0 {
		log.Printf("no reflectable structs found in %s, nothing generated", *dir)
		return
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by gsgen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)
	fmt.Fprintf(&buf, "import gs %q\n", *gspkg)
	for _, w := range weaves {
		emitTrampoline(&buf, w)
	}
	fmt.Fprintf(&buf, "\nfunc init() {\n")
	for _, n := range names {
		fmt.Fprintf(&buf, "\tgs.Register[%s]()\n", n)
	}
	fmt.Fprintf(&buf, "}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("formatting generated code: %v", err)
	}
	path := filepath.Join(*dir, *out)
	if err := os.WriteFile(path, src, 0o644); err != nil {
		log.Fatal(err)
	}
	woven := make([]string, 0, len(weaves))
	for _, w := range weaves {
		woven = append(woven, w.recvType+"."+w.wovenName)
	}
	log.Printf("wrote %s (%d types: %s; %d woven: %s)",
		path, len(names), strings.Join(names, ", "), len(weaves), strings.Join(woven, ", "))
}

func scanFile(file *ast.File) []string {
	var names []string
	for _, decl := range file.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}
		for _, spec := range gd.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			// generic types can't be registered without instantiation
			if ts.TypeParams != nil && len(ts.TypeParams.List) > 0 {
				continue
			}
			if hasMarker(gd.Doc, ts.Doc) || hasGsTag(st) {
				names = append(names, ts.Name.Name)
			}
		}
	}
	return names
}

func scanImpls(file *ast.File, eligible map[string]bool) []weaveFn {
	var weaves []weaveFn
decls:
	for _, decl := range file.Decls {
		fd, ok := decl.(*ast.FuncDecl)
		if !ok || fd.Recv == nil || len(fd.Recv.List) != 1 {
			continue
		}
		name := fd.Name.Name
		if !strings.HasSuffix(name, "Impl") || len(name) == len("Impl") {
			continue
		}
		recv := fd.Recv.List[0]
		star, ok := recv.Type.(*ast.StarExpr)
		if !ok {
			continue
		}
		rid, ok := star.X.(*ast.Ident)
		if !ok || !eligible[rid.Name] {
			continue
		}
		if len(recv.Names) == 0 {
			log.Printf("skipping %s.%s: receiver must be named", rid.Name, name)
			continue
		}

		w := weaveFn{
			recvName: recv.Names[0].Name,
			recvType: rid.Name,
			implName: name,
		}
		base := strings.TrimSuffix(name, "Impl")
		w.wovenName = strings.ToUpper(base[:1]) + base[1:]

		if fd.Type.Params != nil {
			for _, f := range fd.Type.Params.List {
				if len(f.Names) == 0 {
					log.Printf("skipping %s.%s: params must be named", rid.Name, name)
					continue decls
				}
				g := paramGroup{typ: types.ExprString(f.Type)}
				for _, n := range f.Names {
					g.names = append(g.names, n.Name)
				}
				if _, isEllipsis := f.Type.(*ast.Ellipsis); isEllipsis {
					w.variadic = true
				}
				w.params = append(w.params, g)
			}
		}
		if fd.Type.Results != nil {
			for _, f := range fd.Type.Results.List {
				typ := types.ExprString(f.Type)
				n := len(f.Names)
				if n == 0 {
					n = 1
				}
				for i := 0; i < n; i++ {
					w.results = append(w.results, typ)
				}
			}
		}
		weaves = append(weaves, w)
	}
	return weaves
}

func emitTrampoline(buf *bytes.Buffer, w weaveFn) {
	var sig, flat []string
	for _, g := range w.params {
		sig = append(sig, strings.Join(g.names, ", ")+" "+g.typ)
		flat = append(flat, g.names...)
	}
	res := ""
	switch len(w.results) {
	case 0:
	case 1:
		res = " " + w.results[0]
	default:
		res = " (" + strings.Join(w.results, ", ") + ")"
	}

	fmt.Fprintf(buf, "\nfunc (%s *%s) %s(%s)%s {\n",
		w.recvName, w.recvType, w.wovenName, strings.Join(sig, ", "), res)
	fmt.Fprintf(buf, "\tif __p, __ok := gs.Hook(%s, %q); __ok {\n", w.recvName, w.wovenName)

	callArgs := fmt.Sprintf("[]any{%s}", strings.Join(flat, ", "))
	if w.variadic {
		last := flat[len(flat)-1]
		fixed := flat[:len(flat)-1]
		fmt.Fprintf(buf, "\t\t__args := make([]any, 0, %d+len(%s))\n", len(fixed), last)
		if len(fixed) > 0 {
			fmt.Fprintf(buf, "\t\t__args = append(__args, %s)\n", strings.Join(fixed, ", "))
		}
		fmt.Fprintf(buf, "\t\tfor _, __v := range %s {\n\t\t\t__args = append(__args, __v)\n\t\t}\n", last)
		callArgs = "__args"
	}

	forward := strings.Join(flat, ", ")
	if w.variadic {
		forward = strings.Join(append(flat[:len(flat)-1], flat[len(flat)-1]+"..."), ", ")
	}

	if len(w.results) == 0 {
		fmt.Fprintf(buf, "\t\t__p(%s, %s)\n\t\treturn\n\t}\n", w.recvName, callArgs)
		fmt.Fprintf(buf, "\t%s.%s(%s)\n}\n", w.recvName, w.implName, forward)
		return
	}
	fmt.Fprintf(buf, "\t\t__out := __p(%s, %s)\n", w.recvName, callArgs)
	var rets []string
	for i, rt := range w.results {
		fmt.Fprintf(buf, "\t\t__r%d, _ := __out[%d].(%s)\n", i, i, rt)
		rets = append(rets, fmt.Sprintf("__r%d", i))
	}
	fmt.Fprintf(buf, "\t\treturn %s\n\t}\n", strings.Join(rets, ", "))
	fmt.Fprintf(buf, "\treturn %s.%s(%s)\n}\n", w.recvName, w.implName, forward)
}

func hasMarker(docs ...*ast.CommentGroup) bool {
	for _, d := range docs {
		if d == nil {
			continue
		}
		for _, c := range d.List {
			if strings.Contains(c.Text, "gs:register") {
				return true
			}
		}
	}
	return false
}

func hasGsTag(st *ast.StructType) bool {
	if st.Fields == nil {
		return false
	}
	for _, f := range st.Fields.List {
		if f.Tag == nil {
			continue
		}
		raw, err := strconv.Unquote(f.Tag.Value)
		if err != nil {
			continue
		}
		if _, ok := reflect.StructTag(raw).Lookup("gs"); ok {
			return true
		}
	}
	return false
}
