// Code generated by gsgen; DO NOT EDIT.

package main

import gs "github.com/dappermint/glass/gs"

func (g *Greeter) Greet(greeting string) string {
	if __p, __ok := gs.Hook(g, "Greet"); __ok {
		__out := __p(g, []any{greeting})
		__r0, _ := __out[0].(string)
		return __r0
	}
	return g.greetImpl(greeting)
}

func init() {
	gs.Register[Greeter]()
}
